### ISSUE TITLE
args.shuffle_smiles is available?

### ISSUE THREAD

**Issue by JunSeok94** [thomas0809/textreact#1]
Hi, I read your awesome paper and tried to run your code of main branch, but shuffle_smiles is not implemented.

Do you have any plan to update this or tevatron branch is covering this issue?

**Comment by thomas0809** [comment]
Hi,

Thanks for reaching out!

I believe the code for shuffle_smiles is already included in the repo.
https://github.com/thomas0809/textreact/blob/98e7859b9b7b14dddd849aec6234ae39be65d283/textreact/dataset.py#L179-L180
https://github.com/thomas0809/textreact/blob/98e7859b9b7b14dddd849aec6234ae39be65d283/textreact/dataset.py#L230-L231

To use it, add `--shuffle_smiles` to your script.
https://github.com/thomas0809/textreact/blob/98e7859b9b7b14dddd849aec6234ae39be65d283/scripts/train_RCR.sh#L31

Please feel free to let me know if you have other questions!

**Comment by JunSeok94** [comment]
Hi, thanks for quick and kind reply!

https://github.com/thomas0809/textreact/blob/98e7859b9b7b14dddd849aec6234ae39be65d283/textreact/dataset.py#L179-L180

In L180, is it random_shuffle_reaction_smiles is not implemented in its definition now?
https://github.com/thomas0809/textreact/blob/98e7859b9b7b14dddd849aec6234ae39be65d283/textreact/dataset.py#L432-L433

**Comment by uranium11010** [comment]
Thanks for reaching out! The issue was just fixed and `--shuffle_smiles` should work properly now :)

**Comment by JunSeok94** [comment]
Great! Thanks for ultimately quick fix. I look forward to following your new paper!
