### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by liugangcode** [thomas0809/textreact#5]
Thank you for your great contribution. I wonder if you have plans to release the pretrained TextReact model and inference code to facilitate quick adaptation of your model in different applications? Besides, any information about the computation cards and time used to train the model is highly appreciated.

**Comment by thomas0809** [comment]
Hi,

Thanks for reaching out! We've uploaded the TextReact checkpoints to Hugging Face hub: https://huggingface.co/yujieq/TextReact/tree/main.

The models were trained with 4 A6000 GPUs. I cannot recall the exact training time, but it was somewhere between 3-4 hours and 1 day, varying depending on the task.

**Comment by liugangcode** [comment]
Great. Thank you for your quick response and information. I'll look into the model!
